language: go
install: true
sudo: false
go_import_path: github.com/simon/go-request

env:
  global:
  - GO111MODULE=on

matrix:
  include:
  - go: 1.9.x
    script:
    - go get -t -v ./...
    - go test -v github.com/sganon/go-request/...
  - go: 1.10.x
    script:
    - go get -t -v ./...
    - go test -v github.com/sganon/go-request/...
  - go: 1.11.x
    script:
    - go test -v github.com/sganon/go-request/... -coverprofile=coverage.out
